version: '3.8'

services: 

    mongodb:
        image: mongo:latest
        container_name: ${APPLICATION_NAME}
        ports: 
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        volumes:
            - ./.docker/mongodb/${APPLICATION_NAME}/db/:/data/db/
        env_file: 
            - ./.env